source "https://rubygems.org"

gem "metanorma" #, git: "https://github.com/riboseinc/metanorma"
gem "asciidoctor-csand" #, path: "~/src/asciidoctor-csand"
#, git: "https://github.com/riboseinc/asciidoctor-csand"
